LessonsCBS/LessonsCBS/urls.py
"""
Definition of urls for LessonsCBS.
"""

from datetime import datetime
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views


urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),

    # our routes
    path("lesson-two/", include('lesson_two_routes.urls')),
    path("lesson-two-part2/", include('lesson_two_routes_part2.urls')),
    path("lesson-two-responses/", include('lesson_two_responses.urls', namespace='lesson_two_responses')),
    path("lesson-third/", include('lesson_third_templates.urls')),
    path("lesson-fifth/", include('lesson_fifth_forms.urls')),
    path("lesson-sixth/", include('lesson_sixth_ORM.urls')),
    path("lesson-seventh/", include('lesson_seventh_registration.urls')),
    path("lesson-eighth/", include('lesson_eight_ajax.urls')),
]

LessonsCBS/lesson_eight_ajax/urls.py
from django.urls import path
from . import views

app_name = 'lesson_eight_ajax'

urlpatterns = [
    path('', views.MainView.as_view(), name="main"),
    path('register', views.RegisterFormView.as_view(), name="registration"),
    path("login", views.LoginFormView.as_view(), name="login"),
    path("logout", views.LogoutView.as_view(), name="logout"),

    path('validate-email/', views.validate_email),
    path('show-three/', views.show_three, name="show_three"),
    path('show-four/', views.show_four, name="show_four"),
    path('add-human/', views.add_human),

    #url(r'^validate-email' , views.validate_email),
    #url(r'^show-three' , views.show_three),
    #url(r'^show-four' , views.show_four),
    #url(r'^add-human/' , views.add_human),
    ]

LessonsCBS/lesson_eight_ajax/models.py
from django.db import models

# Create your models here.

LessonsCBS/lesson_eight_ajax/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from lesson_sixth_ORM.models import Human


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class HumanForm(forms.ModelForm):
    class Meta:
        model = Human
        fields = [field.name for field in Human._meta.fields]

LessonsCBS/lesson_eight_ajax/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from .forms import HumanForm, UserCreateForm
from lesson_sixth_ORM.models import Human
from django.contrib.auth.models import User

from django.http import HttpResponseRedirect , HttpResponse , JsonResponse

from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm


# Create your views here.

# docs: https://docs.djangoproject.com/en/2.2/topics/auth/#user-authentication-in-django
# docs: https://docs.djangoproject.com/en/2.2/topics/auth/default/#using-the-django-authentication-system
class MainView(TemplateView):
    template_name = 'lesson_eight_ajax/ajax.html'
    human_form = HumanForm
    def get(self, request):
        ctx = {}
        if request.user.is_authenticated:
            all_humans  = Human.objects.all()
            ctx['humans'] = all_humans
            ctx['human_form'] = self.human_form
        return render(request, self.template_name, ctx)


class RegisterFormView(FormView):
    form_class = UserCreateForm
    success_url = reverse_lazy("lesson_eight_ajax:login")
    template_name = "lesson_eight_ajax/registration.html"

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)

    def form_invalid(self, form):
        return super(RegisterFormView, self).form_invalid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm

    # Аналогично регистрации, только используем шаблон аутентификации.
    template_name = "lesson_eight_ajax/login.html"

    # В случае успеха перенаправим на главную.
    success_url = reverse_lazy('lesson_eight_ajax:main')

    def form_valid(self, form):
        # Получаем объект пользователя на основе введённых в форму данных.
        self.user = form.get_user()

        # Выполняем аутентификацию пользователя.
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)

    def form_invalid(self, form):
        return super(LoginFormView, self).form_valid(form)
    

class LogoutView(TemplateView):
    def get(self, request):
        logout(request)

        # После чего, перенаправляем пользователя на главную страницу.
        return redirect("lesson_eight_ajax:main")


# Handlers
def validate_email(request):
    if request.GET:
        email = request.GET.get('email')
        is_taken = User.objects.filter(email=email).exists()
        if is_taken:
            data  = {
                "is_taken" : "На этот почтовый ящик уже зарегистрирован пользователь!"
            }
            return JsonResponse(data)
        else:
            return JsonResponse({'ok': "На этот почтовый адрес не было регистраций"})

def show_three(request):
    first_three = Human.objects.all()[:3].values()
    context  = {
        'elements' : list(first_three)
    }
    return JsonResponse(context)

def show_four(request):
    first_four = Human.objects.all()[:4].values()
    context = {
        'elements': list(first_four)
    }
    return JsonResponse(context)

def add_human(request):
    if request.POST:
        if request.is_ajax():
            name = request.POST['name']
            surname = request.POST['surname']
            birth = request.POST['birth']
            company = request.POST['company']
            position = request.POST['position']
            language = request.POST['language']
            salary = request.POST['salary']
            human = Human.objects.create(name=name,
                                 surname=surname,
                                 birth=birth,
                                 company=company,
                                 position=position,
                                 language=language,
                                 salary=salary
                                 )
            return JsonResponse(human.dict())

LessonsCBS/lesson_eight_ajax/templates/lesson_eight_ajax/ajax.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lesson 8. AJAX</title>
    <link rel="stylesheet" href="{% static 'lesson_eight_ajax/css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>    
    <script src="{% static 'lesson_eight_ajax/js/javascript.js' %}"></script>
</head>
<body>
    <h1>Hello AJAX!</h1>
    {% if user.is_authenticated  %}
        <a class="controls" href="{% url 'lesson_eight_ajax:logout' %}">Exit ({{user.username}})</a>
    {% else %}
        <a class="controls" href="{% url 'lesson_eight_ajax:registration' %}">Registration</a>
        <a class="controls" href="{% url 'lesson_eight_ajax:login' %}">Login</a>
    {% endif %}

    <div class="block-login">{% block login%}{% endblock %}</div>

    {% if user.is_authenticated %}
        <h2>Humans List</h2>
        <table id='table_id' border='1' cellpadding=5>
            <tr style='background-color:blue; color:white;'>
                <td>ID</td>
                <td>Name</td>
                <td>Surname</td>
                <td>Birth</td>
                <td>Company</td>
                <td>Position</td>
                <td>Programming language</td>
                <td>Salary</td>
            </tr>
            {% for elem in humans %}
                <tr>
                    <td>{{elem.id}}</td>
                    <td>{{elem.name}}</td>
                    <td>{{elem.surname}}</td>
                    <td>{{elem.birth}}</td>
                    <td>{{elem.company}}</td>
                    <td>{{elem.position}}</td>
                    <td>{{elem.language}}</td>
                    <td>{{elem.salary}}</td>
                </tr>
            {% endfor %}
        </table>

        <a class="show_link" href='{% url 'lesson_eight_ajax:show_three' %}' id='show-three'>Show first three</a>
        <a class="show_link" href='{% url 'lesson_eight_ajax:show_four' %}' id='show-four'>Show firsh four</a>

        <h2>Add humans form</h2>
        <form id='add-human' action="add-human/" method='post'>
            {% csrf_token %}
            {% for field in human_form %}
            <label for="">{{field.label}}</label>
            <div>{{field}}</div>
            {% endfor %}
            <button type='submit'>Add in table</button>
        </form>

    {% endif %}

</body>
</html>

LessonsCBS/lesson_eight_ajax/templates/lesson_eight_ajax/login.html
{% extends 'lesson_eight_ajax/ajax.html' %}

{% block login %}
    <form class="login" action="" method="post">
        {% csrf_token %}

        {% for field in form %}
            <label>{{field.label}}</label>
            <p>{{field}}</p>
            {% if field.errors %}
                <p>{{field.errors}}</p>
            {% endif %}
        {% endfor %}
        <button type="submit">Login</button>
    </form>

{% endblock %}

LessonsCBS/lesson_eight_ajax/templates/lesson_eight_ajax/registration.html
{% extends 'lesson_eight_ajax/ajax.html' %}

{% block login %}
    <form class="reg" action="{% url 'lesson_eight_ajax:registration' %}" method="post">
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group">
                <label for="">{{field.label}}</label>
                <div>{{field}}</div>
                {% if field.errors %}
                    <p>{{field.errors}}</p>
                {% endif %}
            </div>
        {% endfor %}
        <p id='error-mail'></p>
        <button id='btn' type="submit">Registration</button>
    </form>
{% endblock %}